
syntax on
filetype plugin indent on

set noerrorbells
set belloff=all

if has('win32') || has('win64')
    set runtimepath-=~/vimfiles
    set runtimepath^=~/.vim
    set runtimepath-=~/vimfiles/after
    set runtimepath+=~/.vim/after

    set backup
    set dir=$TMP
    set backupdir=$TMP
    set directory=$TMP
    set noundofile

    set backspace=2
    set backspace=indent,eol,start
endif

" ========================================
" Install Plugins
" ========================================

call plug#begin('~/.vim/bundle')

Plug 'bling/vim-airline'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-fugitive'
Plug 'scrooloose/nerdtree'
Plug 'majutsushi/tagbar'
Plug 'sirver/ultisnips'
Plug 'honza/vim-snippets'
Plug 'tpope/vim-surround'
Plug 'flazz/vim-colorschemes'
"Plug '~/.vim/bundle/jupakevim'
Plug 'nelsonjchen/vim-carto'
Plug 'sirtaj/vim-openscad'
Plug 'stephpy/vim-yaml'
Plug 'vim-scripts/haproxy'
Plug 'vimwiki/vimwiki'
Plug 'liuchengxu/vista.vim'

call plug#end()

" ========================================
" Setup main settings
" ========================================

set shiftwidth=4
set tabstop=4
set expandtab
set softtabstop=4

set ignorecase
set hlsearch
set incsearch
set number

set background=dark

"=========================================
" Color Scheme settings
"=========================================
"
"augroup VimwikiBadwolfHeaders
"  autocmd!
"  autocmd ColorScheme badwolf highlight VimwikiHeader1 guifg=#ffa724 ctermfg=214 gui=bold cterm=bold " orange
"  autocmd ColorScheme badwolf highlight VimwikiHeader2 guifg=#aeee00 ctermfg=154 gui=bold cterm=bold " lime
"  autocmd ColorScheme badwolf highlight VimwikiHeader3 guifg=#0a9dff ctermfg=39  gui=bold cterm=bold " tardis
"  autocmd ColorScheme badwolf highlight VimwikiHeader4 guifg=#ff9eb8 ctermfg=211 gui=bold cterm=bold " dress
"  autocmd ColorScheme badwolf highlight VimwikiHeader5 guifg=#b88853 ctermfg=137 gui=bold cterm=bold " toffee
"  autocmd ColorScheme badwolf highlight VimwikiHeader6 guifg=#8cffba ctermfg=121 gui=bold cterm=bold " saltwatertaffy
"augroup END

augroup VimwikiBadwolfHeaders
  autocmd!

  autocmd ColorScheme badwolf highlight VimwikiHeader1 guifg=#aeee00 ctermfg=154 gui=bold cterm=bold " lime
  autocmd ColorScheme badwolf highlight VimwikiHeader2 guifg=#0a9dff ctermfg=39  gui=bold cterm=bold " tardis
  autocmd ColorScheme badwolf highlight VimwikiHeader3 guifg=#ffa724 ctermfg=214 gui=bold cterm=bold " orange
  autocmd ColorScheme badwolf highlight VimwikiHeader4 guifg=#ff9eb8 ctermfg=211 gui=bold cterm=bold " dress
  autocmd ColorScheme badwolf highlight VimwikiHeader5 guifg=#b88853 ctermfg=137 gui=bold cterm=bold " toffee
  autocmd ColorScheme badwolf highlight VimwikiHeader6 guifg=#8cffba ctermfg=121 gui=bold cterm=bold " saltwatertaffy
augroup END

colorscheme badwolf

"=========================================
" Other Settings
"=========================================

set foldmethod=expr


autocmd FileType text setlocal textwidth=80
autocmd FileType python setlocal textwidth=80

autocmd BufRead,BufNewFile *.tal set filetype=html
au BufRead,BufNewFile haproxy* set ft=haproxy
au BufRead,BufNewFile *.map set ft=map

inoremap jj <Esc>

set t_Co=256

set encoding=utf-8

"========================================
" My mappings
"========================================

map <C-C> :
map <F2> :NERDTreeToggle<CR>
map <F3> :NERDTreeFind<CR>

map k <M-k>
map j <M-j>

noremap <M-k> <Esc><Esc><Esc><Esc><C-W>k<C-W>_
noremap <M-j> <Esc><Esc><Esc><Esc><C-W>j<C-W>_

"========================================
"force myself to use vim properly
"========================================
map <Up> <nop>
map <Down> <nop>
map <Left> <nop>
map <Right> <nop>

imap <Up> <nop>
imap <Down> <nop>
imap <Left> <nop>
imap <Right> <nop>
"========================================
" CtrlP settings
"========================================

map <C-p> :CtrlP

let g:ctrlp_match_window = 'bottom:order:btt,max:25'
let g:ctrlp_working_path_mode = 'a'
let g:ctrlp_custom_ignore = {
\ 'dir':  '\v([\/]\.(git|hg|svn)|vendor)$',
\ 'file': '\v\.(exe|so|dll)$',
\ }
let g:ctrlp_extensions = ['ideactions']

nnoremap <leader>ia :CtrlPActions<CR>

"=========================================
" Vimwiki Settings
"=========================================

let main_wiki = {}
let main_wiki.name = 'Main'
let main_wiki.path = '~/Documents/vimwiki'
let main_wiki.path_html = '~/publit_html/vimwiki'
let main_wiki.auto_toc = 1
let main_wiki.syntax = 'markdown'
let main_wiki.ext = '.md'

let g:vimwiki_list = [main_wiki]

let g:vimwiki_global_ext = 0
let g:vimwiki_ext2syntax = {}
"let g:vimwiki_folding = 'list'
let g:vimwiki_folding = ''

"let g:vimwiki_list = [{'path': '~/Dropbox/vimwiki/', 'syntax': 'markdown', 'ext': 'md'}]

"=========================================
" Ultisnips
"=========================================

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsEditSplit="vertical"

autocmd VimEnter * wincmd p

