#!/usr/bin/python

import sys

data = []
max_width = 0

for line in sys.stdin:
    front, back = line.split('=')
    max_width = max(max_width, len(front.rstrip()))
    data.append( (front.rstrip(), back) )

final_data = []
for front, back in data:
    newline = '{} = {}'.format(front.ljust(max_width), back)
    final_data.append(newline)


for line in final_data:
    print line,
    




